import { parseThemeColors, BASE_VARIABLES } from "./themes";

export interface BuildPlanInput {
  projectName: string;
  initialPrompt: string;
  userInstructions: string;
  deviceType: string;
  themeName: string;
  themeStyle: string;
  fontFamily: string;
  fontUrl: string;
  fontCategory: string;
  frames: Array<{ title: string; fullHtml: string }>;
}

/**
 * Generates a comprehensive .md implementation plan from a design project.
 * The output is designed for AI coding agents (Cursor, Claude Code, etc.)
 * to build a full application with identical design.
 */
export function generateBuildPlan(input: BuildPlanInput): string {
  const {
    projectName,
    initialPrompt,
    userInstructions,
    deviceType,
    themeName,
    themeStyle,
    fontFamily,
    fontUrl,
    fontCategory,
    frames,
  } = input;

  const sections: string[] = [];

  // ── Title ──
  sections.push(`# ${projectName} — AI Implementation Plan\n`);
  sections.push(
    "> This document was auto-generated by Gimble Design. It contains everything an AI coding agent needs to build this application with an identical design.\n"
  );

  // ── Project Overview ──
  sections.push(`## Project Overview\n`);
  sections.push(`| Field | Value |`);
  sections.push(`|-------|-------|`);
  sections.push(`| **Project Name** | ${projectName} |`);
  sections.push(
    `| **Device Target** | ${formatDeviceType(deviceType)} |`
  );
  sections.push(`| **Total Screens** | ${frames.length} |`);
  sections.push(`| **Theme** | ${themeName} |`);
  sections.push(`| **Primary Font** | ${fontFamily} (${fontCategory}) |`);
  sections.push("");

  if (initialPrompt) {
    sections.push(`### Original Design Prompt`);
    sections.push(`> ${initialPrompt}\n`);
  }

  // ── User Instructions ──
  if (userInstructions) {
    sections.push(`## Your Instructions\n`);
    sections.push(`> ${userInstructions}\n`);
  }

  // ── Recommended Tech Stack ──
  sections.push(`## Recommended Tech Stack\n`);
  sections.push(getTechStackRecommendation(deviceType));
  sections.push("");

  // ── Design Tokens & Theme ──
  sections.push(`## Design Tokens & Theme\n`);
  sections.push(
    "Use these tokens to configure your Tailwind CSS theme or CSS variables so the built app matches the design exactly.\n"
  );

  // Colors from theme
  const themeColors = parseThemeColors(themeStyle);
  if (Object.keys(themeColors).length > 0) {
    sections.push(`### Colors\n`);
    sections.push(`| CSS Variable | Value |`);
    sections.push(`|-------------|-------|`);
    for (const [key, value] of Object.entries(themeColors)) {
      sections.push(`| \`--${key}\` | \`${value}\` |`);
    }
    sections.push("");
  }

  // Base variables (shadows, spacing, tracking)
  const baseTokens = parseThemeColors(BASE_VARIABLES);
  if (Object.keys(baseTokens).length > 0) {
    sections.push(`### Shadows & Spacing\n`);
    sections.push(`| CSS Variable | Value |`);
    sections.push(`|-------------|-------|`);
    for (const [key, value] of Object.entries(baseTokens)) {
      // Skip font variables — we handle those separately
      if (key.startsWith("font-")) continue;
      sections.push(`| \`--${key}\` | \`${value}\` |`);
    }
    sections.push("");
  }

  // Typography
  sections.push(`### Typography\n`);
  sections.push(`- **Primary Font:** \`${fontFamily}\` (${fontCategory})`);
  if (fontUrl) {
    sections.push(`- **Google Fonts URL:** \`${fontUrl}\``);
  }
  sections.push(
    `- **Font Import:** Add to your \`<head>\` or CSS: \`@import url('${fontUrl}');\``
  );
  sections.push("");

  // ── Screen-by-Screen Breakdown ──
  sections.push(`## Screens\n`);
  sections.push(
    `Below is the full HTML implementation for each screen. Each screen is a self-contained page with all styles, fonts, and theme tokens included. Use these as the **pixel-perfect reference** when building each page/route.\n`
  );

  frames.forEach((frame, index) => {
    sections.push(`### Screen ${index + 1}: ${frame.title}\n`);
    sections.push("```html");
    sections.push(frame.fullHtml);
    sections.push("```\n");
  });

  // ── Component Architecture ──
  sections.push(`## Suggested Component Architecture\n`);
  sections.push(getComponentArchitecture(frames, deviceType));
  sections.push("");

  // ── Implementation Steps ──
  sections.push(`## Implementation Steps\n`);
  sections.push(
    "Follow these steps in order. Each step builds on the previous one.\n"
  );
  sections.push(getImplementationSteps(frames, deviceType, fontFamily, themeName));
  sections.push("");

  // ── Important Notes ──
  sections.push(`## Important Notes\n`);
  sections.push(
    `- The HTML above uses **Tailwind CSS** classes — configure your project with Tailwind CSS.`
  );
  sections.push(
    `- Theme colors use **CSS custom properties** (variables). Set them in your global CSS \`:root\` block.`
  );
  sections.push(
    `- Icons use the **Iconify** library (\`<iconify-icon>\` web component). Install \`@iconify/react\` for React or use the CDN.`
  );
  sections.push(
    `- The HTML is the **source of truth** for layout and styling. Match it as closely as possible.`
  );
  sections.push(
    `- Images in the design are placeholder URLs. Replace them with your actual assets.`
  );
  sections.push("");

  sections.push("---");
  sections.push(
    "*Generated by [Gimble Design](https://gimbledesign.vercel.app)*"
  );

  return sections.join("\n");
}

// ── Helpers ──

function formatDeviceType(deviceType: string): string {
  switch (deviceType) {
    case "mobile":
      return "Mobile (responsive, mobile-first)";
    case "web":
      return "Web / Desktop (responsive)";
    case "wireframe":
      return "Wireframe (implement with full styling)";
    case "inspirations":
      return "Custom Dimensions (inspiration-based)";
    default:
      return deviceType;
  }
}

function getTechStackRecommendation(deviceType: string): string {
  const lines: string[] = [];

  lines.push("| Technology | Recommendation |");
  lines.push("|-----------|---------------|");
  lines.push("| **Framework** | Next.js 14+ (App Router) |");
  lines.push("| **Styling** | Tailwind CSS v3/v4 |");
  lines.push("| **Language** | TypeScript |");
  lines.push("| **Icons** | Iconify (`@iconify/react`) |");

  if (deviceType === "mobile") {
    lines.push("| **Approach** | Mobile-first responsive design |");
    lines.push(
      "| **Alternative** | React Native / Expo if building a native app |"
    );
  } else if (deviceType === "web") {
    lines.push("| **Approach** | Desktop-first with responsive breakpoints |");
  } else if (deviceType === "wireframe") {
    lines.push(
      "| **Note** | This is a wireframe — add polish, shadows, and animations during implementation |"
    );
  }

  return lines.join("\n");
}

function getComponentArchitecture(
  frames: Array<{ title: string }>,
  deviceType: string
): string {
  const lines: string[] = [];

  lines.push("```");
  lines.push("src/");
  lines.push("├── app/");
  lines.push("│   ├── layout.tsx          # Root layout with theme CSS variables & font");
  lines.push("│   ├── globals.css         # Global styles, CSS variables, Tailwind imports");

  frames.forEach((frame) => {
    const slug = frame.title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "");
    const routeName = slug === "home" || slug === "landing" ? "" : slug;
    if (routeName) {
      lines.push(
        `│   ├── ${routeName}/page.tsx   # ${frame.title} screen`
      );
    } else {
      lines.push(
        `│   ├── page.tsx               # ${frame.title} screen (home route)`
      );
    }
  });

  lines.push("│");
  lines.push("├── components/");
  lines.push("│   ├── ui/                 # Reusable UI primitives (Button, Card, Input, etc.)");

  if (frames.length > 1) {
    lines.push("│   ├── layout/");

    if (deviceType === "mobile") {
      lines.push("│   │   ├── mobile-nav.tsx   # Bottom navigation bar");
      lines.push("│   │   └── header.tsx       # Top app header");
    } else {
      lines.push("│   │   ├── navbar.tsx       # Top navigation bar");
      lines.push("│   │   ├── sidebar.tsx      # Side navigation (if applicable)");
      lines.push("│   │   └── footer.tsx       # Page footer");
    }
  }

  lines.push("│");
  lines.push("├── lib/");
  lines.push("│   └── utils.ts            # Utility functions (cn, formatters, etc.)");
  lines.push("│");
  lines.push("└── public/");
  lines.push("    └── images/             # Static assets & images");
  lines.push("```");

  return lines.join("\n");
}

function getImplementationSteps(
  frames: Array<{ title: string }>,
  deviceType: string,
  fontFamily: string,
  themeName: string
): string {
  const lines: string[] = [];
  let step = 1;

  lines.push(
    `${step++}. **Initialize the project** — Run \`npx create-next-app@latest\` with TypeScript and Tailwind CSS enabled.`
  );
  lines.push(
    `${step++}. **Configure Tailwind CSS** — Extend the Tailwind config with the CSS custom properties from the Design Tokens section above. Map \`--primary\`, \`--background\`, \`--foreground\`, etc. to Tailwind color utilities.`
  );
  lines.push(
    `${step++}. **Set up the font** — Add \`${fontFamily}\` via Google Fonts in your root layout. Apply it as the default body font.`
  );
  lines.push(
    `${step++}. **Create the root layout** — In \`app/layout.tsx\`, set up the \`:root\` CSS variables from the "${themeName}" theme (see Design Tokens above). Include the font, meta tags, and global styles.`
  );
  lines.push(
    `${step++}. **Install Iconify** — Run \`npm install @iconify/react\` and replace any \`<iconify-icon>\` elements with the React component equivalent.`
  );

  if (frames.length > 1) {
    lines.push(
      `${step++}. **Build shared layout components** — Extract the navigation ${deviceType === "mobile" ? "(bottom tab bar / header)" : "(navbar / sidebar / footer)"} that appears across screens into reusable layout components.`
    );
  }

  frames.forEach((frame) => {
    lines.push(
      `${step++}. **Implement "${frame.title}" screen** — Translate the HTML reference above into React/Next.js components. Use Tailwind classes from the HTML. Break large sections into sub-components.`
    );
  });

  lines.push(
    `${step++}. **Extract reusable components** — Identify repeated UI patterns (buttons, cards, inputs, badges) across screens and extract them into \`components/ui/\`.`
  );
  lines.push(
    `${step++}. **Add interactivity** — Wire up navigation between screens, form handling, and any dynamic behavior.`
  );
  lines.push(
    `${step++}. **Replace placeholder images** — Swap placeholder/stock image URLs with your actual assets in \`public/images/\`.`
  );
  lines.push(
    `${step++}. **Test & polish** — Test all screens on ${deviceType === "mobile" ? "mobile viewports" : "desktop and mobile viewports"}. Verify colors, fonts, spacing, and layout match the HTML references exactly.`
  );

  return lines.join("\n");
}
